PRAGMA foreign_keys=ON;
CREATE TABLE peers(id TEXT PRIMARY KEY, alias TEXT NOT NULL, last_seen INTEGER, public_key BLOB NOT NULL, method TEXT NOT NULL);
CREATE TABLE chats(id TEXT PRIMARY KEY, name TEXT NOT NULL, is_group INTEGER NOT NULL, encryption_key BLOB NOT NULL, image_hash TEXT);
CREATE TABLE files(file_hash TEXT PRIMARY KEY, file_name TEXT, mime_type TEXT, size_bytes INTEGER, is_complete BOOLEAN);
CREATE TABLE file_chunks(file_hash TEXT NOT NULL, chunk_order INTEGER NOT NULL, chunk_hash TEXT NOT NULL, chunk_size INTEGER NOT NULL, PRIMARY KEY(file_hash,chunk_order), FOREIGN KEY(file_hash) REFERENCES files(file_hash));
CREATE TABLE messages(id TEXT PRIMARY KEY, chat_id TEXT NOT NULL, peer_id TEXT NOT NULL, timestamp INTEGER NOT NULL, content_type TEXT NOT NULL, text_content TEXT, file_hash TEXT, status TEXT NOT NULL, content_metadata TEXT, sender_alias TEXT, FOREIGN KEY(chat_id) REFERENCES chats(id), FOREIGN KEY(peer_id) REFERENCES peers(id), FOREIGN KEY(file_hash) REFERENCES files(file_hash));
CREATE TABLE group_records(id TEXT PRIMARY KEY, group_id TEXT NOT NULL, record_type TEXT NOT NULL, author_peer_id TEXT NOT NULL, timestamp INTEGER NOT NULL, payload_json TEXT NOT NULL, public_key_b64 TEXT NOT NULL, signature_b64 TEXT NOT NULL, verified INTEGER NOT NULL, pending INTEGER NOT NULL, received_at INTEGER NOT NULL);
CREATE TABLE group_invites(invite_id TEXT PRIMARY KEY, group_id TEXT NOT NULL, group_name TEXT NOT NULL, inviter_peer_id TEXT NOT NULL, invitee_peer_id TEXT NOT NULL, status TEXT NOT NULL, payload_json TEXT NOT NULL, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE TABLE group_message_receipts(message_id TEXT NOT NULL, group_id TEXT NOT NULL, peer_id TEXT NOT NULL, status TEXT NOT NULL, timestamp INTEGER NOT NULL, PRIMARY KEY(message_id,peer_id));
CREATE TABLE envelopes(id TEXT PRIMARY KEY, name TEXT NOT NULL, icon TEXT);
CREATE TABLE chat_envelopes(chat_id TEXT PRIMARY KEY, envelope_id TEXT NOT NULL, FOREIGN KEY(envelope_id) REFERENCES envelopes(id));
INSERT INTO peers VALUES('peer-a','Alice',12,X'0001FF','manual');
INSERT INTO chats VALUES('direct-a','Alice',0,X'ABCD',NULL),('group:a','Group',1,X'1234',NULL),('archive:a','Archived',0,X'5678',NULL);
INSERT INTO files VALUES('ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad','a.txt','text/plain',3,1);
INSERT INTO file_chunks VALUES('ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad',0,'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad',3);
INSERT INTO messages VALUES('dm','direct-a','peer-a',1,'text','hello',NULL,'read',NULL,'Alice'),('gm','group:a','peer-a',2,'text','group',NULL,'delivered',NULL,'Alice'),('am','archive:a','peer-a',3,'document',NULL,'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad','read',NULL,'Historical Alice');
INSERT INTO group_records VALUES('record-a','group:a','message','peer-a',2,'{"preserve":"signed bytes"}','public','signature',1,0,2);
INSERT INTO group_message_receipts VALUES('gm','group:a','peer-a','read',3);
INSERT INTO group_invites VALUES('invite-a','group:a','Group','peer-a','peer-b','pending','{"preserve":"invite"}',1,2);
INSERT INTO envelopes VALUES('archive','Archive',NULL);
INSERT INTO chat_envelopes VALUES('archive:a','archive');
